"""
Roadmap 4.1 tests — ContentProfile extraction (ADR-011).

The Analyzer must pull real signals out of file content using the standard
library only (no spaCy, no OCR deps):
- PDF: text extracted from (possibly FlateDecode-compressed) content streams
- PNG: dimensions from IHDR + textual metadata from tEXt chunks
- JPEG: APP1 EXIF presence + SOF dimensions
- code: shebang + language keyword detection
- archives: manifest of member names (zip/tar)
- everything else degrades to a typed profile, never an exception
"""
import struct
import zlib
from pathlib import Path

import pytest

from src.core.analyzer import extract_profile, ContentProfile


# ---------------------------------------------------------------------------
# fixture builders (stdlib only, same technique as demo/make_samples.py)
# ---------------------------------------------------------------------------

def _png_chunk(chunk_type: bytes, data: bytes) -> bytes:
    return (
        struct.pack(">I", len(data))
        + chunk_type
        + data
        + struct.pack(">I", zlib.crc32(chunk_type + data) & 0xFFFFFFFF)
    )


def make_png(width: int = 16, height: int = 16, with_text: bool = False) -> bytes:
    """Valid PNG; optionally carries a tEXt keyword/value pair."""
    pixels = b"\x42\x2a\x66" * (width * height)  # uniform RGB
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    raw = b"".join(b"\x00" + pixels[y * width * 3:(y + 1) * width * 3] for y in range(height))
    out = (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", ihdr)
        + _png_chunk(b"IDAT", zlib.compress(raw))
    )
    if with_text:
        out += _png_chunk(b"tEXt", b"Comment\x00generated by test fixture")
    out += _png_chunk(b"IEND", b"")
    return out


def make_pdf(lines: list) -> bytes:
    """Minimal 1-page PDF with visible text (uncompressed content stream)."""
    content = "\n".join(
        f"BT /F1 12 Tf 72 {y} Td ({line}) Tj ET" for y, line in zip(range(720, 120, -20), lines)
    )
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
        f"<< /Length {len(content.encode())} >>\nstream\n{content}\nendstream".encode(),
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + obj + b"\nendobj\n"
    xref_pos = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for off in offsets[1:]:
        out += f"{off:010d} 00000 n \n".encode()
    out += f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_pos}\n%%EOF\n".encode()
    return bytes(out)


# ---------------------------------------------------------------------------
# pdf -> text
# ---------------------------------------------------------------------------

def test_pdf_profile_extracts_text(tmp_path):
    pdf = tmp_path / "invoice.pdf"
    pdf.write_bytes(make_pdf(["INVOICE - Amazon", "Total: 42.00", "Thank you"]))

    profile = extract_profile(pdf)

    assert profile.kind == "pdf"
    assert "INVOICE" in profile.text_sample
    assert "Total" in profile.text_sample


def test_pdf_profile_extracts_text_from_compressed_stream(tmp_path):
    """FlateDecode streams must be decompressed (zlib) before text extraction."""
    text = b"CONFIDENTIAL REPORT 2026"
    stream = f"<< /Length {len(zlib.compress(text))} /Filter /FlateDecode >>\nstream\n".encode() + zlib.compress(text) + b"\nendstream"
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>",
        stream,
    ]
    out = bytearray(b"%PDF-1.4\n")
    for i, obj in enumerate(objects, start=1):
        out += f"{i} 0 obj\n".encode() + obj + b"\nendobj\n"
    out += b"trailer\n<< /Size 5 /Root 1 0 R >>\n%%EOF\n"
    pdf = tmp_path / "compressed.pdf"
    pdf.write_bytes(bytes(out))

    profile = extract_profile(pdf)

    assert profile.kind == "pdf"
    assert "CONFIDENTIAL" in profile.text_sample


# ---------------------------------------------------------------------------
# images
# ---------------------------------------------------------------------------

def test_png_profile_gets_dimensions(tmp_path):
    img = tmp_path / "photo.png"
    img.write_bytes(make_png(16, 32))

    profile = extract_profile(img)

    assert profile.kind == "image"
    assert profile.dimensions == (16, 32)


def test_png_profile_reads_text_metadata(tmp_path):
    img = tmp_path / "annotated.png"
    img.write_bytes(make_png(with_text=True))

    profile = extract_profile(img)

    assert profile.kind == "image"
    assert "generated by test fixture" in profile.metadata.get("text", "")


def test_jpeg_profile_detects_exif_and_dimensions(tmp_path):
    # Minimal APP0 (JFIF) + APP1 (Exif) + SOF0 (16x32) + EOI.
    # Segment length fields include their own 2 bytes (standard JPEG).
    jpg = (
        b"\xff\xd8"
        + b"\xff\xe0" + struct.pack(">H", 16)
        + b"JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00"
        + b"\xff\xe1" + struct.pack(">H", 16)
        + b"Exif\x00\x00" + b"\x00" * 8
        + b"\xff\xc0" + struct.pack(">H", 17)
        + b"\x08" + struct.pack(">HH", 32, 16) + b"\x03\x01\x11\x00\x02\x11\x01\x03\x11\x01"
        + b"\xff\xd9"
    )
    img = tmp_path / "snap.jpg"
    img.write_bytes(jpg)

    profile = extract_profile(img)

    assert profile.kind == "image"
    assert profile.dimensions == (16, 32)
    assert profile.metadata.get("has_exif") is True


# ---------------------------------------------------------------------------
# code / text
# ---------------------------------------------------------------------------

def test_code_profile_detects_shebang_and_language(tmp_path):
    script = tmp_path / "tool.py"
    script.write_text("#!/usr/bin/env python3\nimport os\ndef main():\n    return 0\n")

    profile = extract_profile(script)

    assert profile.kind == "code"
    assert "python" in profile.metadata.get("language", "")
    assert "python" in profile.metadata.get("shebang", "")


def test_text_profile_for_prose(tmp_path):
    note = tmp_path / "note.md"
    note.write_text("# Meeting Notes\nDecide on the Q3 budget allocation.")

    profile = extract_profile(note)

    assert profile.kind == "text"
    assert "Meeting" in profile.text_sample


# ---------------------------------------------------------------------------
# archives
# ---------------------------------------------------------------------------

def test_zip_profile_lists_manifest(tmp_path):
    import zipfile
    z = tmp_path / "bundle.zip"
    with zipfile.ZipFile(z, "w") as zf:
        zf.writestr("a.txt", "hello")
        zf.writestr("b/c.txt", "world")

    profile = extract_profile(z)

    assert profile.kind == "archive"
    assert "a.txt" in profile.metadata["members"]
    assert "b/c.txt" in profile.metadata["members"]


def test_tar_profile_lists_manifest(tmp_path):
    import tarfile
    t = tmp_path / "bundle.tar"
    with tarfile.open(t, "w") as tf:
        for name in ("one.txt", "two.txt"):
            data = b"x"
            info = tarfile.TarInfo(name)
            info.size = len(data)
            tf.addfile(info, __import__("io").BytesIO(data))

    profile = extract_profile(t)

    assert profile.kind == "archive"
    assert set(profile.metadata["members"]) == {"one.txt", "two.txt"}


# ---------------------------------------------------------------------------
# degradation
# ---------------------------------------------------------------------------

def test_unknown_binary_profile_never_raises(tmp_path):
    blob = tmp_path / "opaque.xyz"
    blob.write_bytes(b"\x00\x01\x02\xff" * 16)

    profile = extract_profile(blob)

    assert profile.kind in ("binary", "unknown")
    assert isinstance(profile, ContentProfile)


def test_missing_file_raises(tmp_path):
    with pytest.raises(FileNotFoundError):
        extract_profile(tmp_path / "absent.pdf")